[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[Workspace]



[dependencies]
arkworks-setups = "1.2.2"
ndarray = "0.15.6"
